chat_model:
    google: 
        # Gemini 2.5 Pro: gemini-2.5-pro
        # Gemini 2.5 Flash: gemini-2.5-flash
        Gemini 2.0 Flash: gemini-2.0-flash
        # Gemini 2.0 Flash-Lite: gemini-2.0-flash-lite
    ollama:
        Meta's Llama 3.2 3B: llama3.2
        # Mistral 7B: mistral:7b

embedding_model:
    google: 
        Gecko: text-embedding-005   
    ollama: 
        Mixedbread.ai large: mxbai-embed-large

preprocessor:
    type: sentence_chunker
    embedding_model: all-MiniLM-L6-v2
    chunk_size: 500
    min_sentences: 5
