retriever:
    group1:       
        google: 'text-embedding-004'
        hyperparameters:
            max_retries: 2
            temperature: 0.1
    group2:       
        google: 'text-embedding-005'
        hyperparameters: 
    metrics:
        ContextualRecallMetric:
        ContextualPrecisionMetric:
    eval_model: 
        google: 'gemini-2.5-pro-preview-03-25'
        hyperparameters:
generation:
    group1:       
        google: 'gemini-2.5-pro-preview-03-25'
        hyperparameters:
    group2:       
        google: 'gemini-2.0-flash-001'
        hyperparameters:
    metrics:
        AnswerRelevancyMetric:
        FaithfulnessMetric:
    eval_model: 
        google: 'gemini-2.5-flash-preview-04-17'
        hyperparameters:
    embedding_model:
        google: 'text-embedding-005'
        hyperparameters:
